### ISSUE TITLE
Document is not defined

### ISSUE THREAD

**Issue by thorakmedichi** [rayandrews/react-native-web-modal#13]
I am getting the following error when running `yarn android`
![screenshot_20190214_123330](https://user-images.githubusercontent.com/5092843/52816131-72546e00-3055-11e9-8fec-4c603c4ad4ae.png)

I have added this to my webpack config to try and solve the issue but still no luck
```
alias: {
            // Support React Native Web
            // https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/
            'react-native': 'react-native-web',
            'react-native-modal': 'modal-enhanced-react-native-web'
        },
```

here are my package.json dependencies
```
"dependencies": {
    "axios": "^0.18.0",
    "immutability-helper": "^3.0.0",
    "lodash": "^4.17.11",
    "modal-enhanced-react-native-web": "^0.2.0",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.23",
    "prop-types": "^15.6.0",
    "prop-types-defined": "^15.6.0",
    "react": "^16.6.x",
    "react-app-polyfill": "^0.1.3",
    "react-art": "^16.6.x",
    "react-dom": "^16.6.x",
    "react-native": "0.55.x",
    "react-native-elements": "^1.0.0",
    "react-native-vector-icons": "^6.2.0",
    "react-native-web": "^0.9.x",
    "react-native-windows": "^0.50.0",
    "react-redux": "5.0.6",
    "react-router": "4.2.0",
    "react-router-dom": "4.2.2",
    "react-router-native": "4.2.0",
    "redux": "3.7.2",
    "redux-persist": "^5.10.0",
    "redux-thunk": "2.2.0",
    "reselect": "^4.0.0"
  },
```

Not sure what to do next to resolve this issue.

**Comment by arthurpankiewicz** [comment]
Same error for me - running on High Sierra

**Comment by rayandrew** [comment]
Hello, thanks for issuing the problem.

This modal cannot be used for React Native. It is purely build for web. So if you want to use `modal-enhanced-react-native-web`, just install [React Native Modal](https://github.com/react-native-community/react-native-modal). 

`modal-enhanced-react-native-web` is ported from [React Native Modal](https://github.com/react-native-community/react-native-modal).

If you develop and build for web and mobile, then specify in your webpack to use `modal-enhanced-react-native-web` for web and [React Native Modal](https://github.com/react-native-community/react-native-modal) for native.

I hope it will fix your issue.

**Also duplicate** #8

**Comment by thorakmedichi** [comment]
Can I ask why this is called "React NATIVE Web Modal" if it does not work for React Native? 

This name is really incorrect if what you say is true

**Comment by petrbela** [comment]
> Can I ask why this is called "React NATIVE Web Modal" if it does not work for React Native?
> 
> This name is really incorrect if what you say is true

`react-native-web` is a React port of React Native, and as the name suggests, it is made for the web. It doesn't work in native because that's what React Native already does. In a similar fashion, it's a common practice to name web versions of native components `react-native-web-something` because they patch the component for web. So yes, it could be documented slightly better but the name at least makes logical sense :)
