### ISSUE TITLE
built packages don't tree shake react-native-web

### ISSUE THREAD

**Issue by awinograd** [rayandrews/react-native-web-modal#14]
When the packages are built with babel, they end up requiring all of `react-native-web` without tree shaking unused code. This means for an app consuming one of the modal packages, there's not way to tree shake `rnw` because there is a dependency that "requires" all of the package.

**Comment by mschipperheyn** [comment]
I'm not sure if this will work, but you can try the babel-plugin-import plugin
```
[
    "import",
    Object.assign(
      {},
      {
        'modal-react-native-web'
      },
      {
                libraryDirectory: resolveNodeModules('modal-react-native-web'),
	       camel2DashComponentName: false,
      }
    ),
    `fix-modal-react-native-web-imports`
  ]
```

**Comment by EyMaddis** [comment]
It should use the [babel plugin for react-native-web](https://www.npmjs.com/package/babel-plugin-react-native-web) instead of aliasing.

`import { StyleSheet } from 'react-native'` 
translates to
`import StyleSheet from 'react-native/dist/exports/StyleSheet'`

**Comment by rayandrew** [comment]
modal is now supported in react native web.

https://github.com/necolas/react-native-web/releases/tag/0.14.0

Thank you for using this library!

<blockquote><img src="https://avatars3.githubusercontent.com/u/239676?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/necolas/react-native-web/releases/tag/0.14.0">Release 0.14.0 · necolas/react-native-web</a></strong></div><div>This is a relatively small release that introduces a couple of new features and makes a change to the default flexBasis value of View. There are no breaking API changes and it should be straight-fo...</div></blockquote>
