### ISSUE TITLE
Style properties not processed

### ISSUE THREAD

**Issue by mschipperheyn** [rayandrews/react-native-web-modal#17]
I have this component. I can see the styles applied in the debugger but they are not applied on screen. When I change the value from red to blue in React devtools, it works. For some reason, styles don't seem to be processed, on first pass the modal content background remains transparent, despite the `contentContainer`.

```
import React, { useState } from 'react';
import { StyleSheet, Dimensions } from 'react-native';
import Modal from 'modal-enhanced-react-native-web';
import useEventListener from 'common-lib/src/hooks/useEventListener';

// presentationStyle is not yet supported :-(

const MyModal = ({ visible, style, children, ...rest }) => {
	const [width, setWidth] = useState(Dimensions.get('window').width);
	useEventListener(
		'change',
		({ window }) => {
			setWidth(window.width);
		},
		Dimensions
	);

	return (
		<Modal
			isVisible={visible}
			style={[
				width > 375 && styles.maxWidth,
				styles.contentContainer,
				style,
			]}
			{...rest}
		>
			{children}
		</Modal>
	);
};

const styles = StyleSheet.create({
	contentContainer: {
		backgroundColor: 'red',
	},
	maxWidth: {
		width: 375,
	},
});

export default MyModal;

```

<img width="541" alt="Screenshot 2019-04-10 at 14 02 36" src="https://user-images.githubusercontent.com/384959/55898654-73a7a000-5b99-11e9-805f-aa6fa226ff97.png">

**Comment by mschipperheyn** [comment]
Could this be because the library is supplied in compiled es5 format?

**Comment by rayandrew** [comment]
I will see whether I can solve the issue, got really tight schedule. Will update it if I have chance

**Comment by rayandrew** [comment]
modal is now supported in react native web.

https://github.com/necolas/react-native-web/releases/tag/0.14.0

Thank you for using this library!

<blockquote><img src="https://avatars3.githubusercontent.com/u/239676?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/necolas/react-native-web/releases/tag/0.14.0">Release 0.14.0 · necolas/react-native-web</a></strong></div><div>This is a relatively small release that introduces a couple of new features and makes a change to the default flexBasis value of View. There are no breaking API changes and it should be straight-fo...</div></blockquote>
