### ISSUE TITLE
Margin is present around all modals, control this margin

### ISSUE THREAD

**Issue by ziaulrehman40** [rayandrews/react-native-web-modal#18]
Hi there, I am using `modal-enhanced-react-native-web`, and i can see some margin on all 4 sides of pages, the margin is dynamic, applies as per screen size(doesn't change in real time on screen size change though).

This margin is causing styling issues, is there a way to control this margin?

<img width="278" alt="image" src="https://user-images.githubusercontent.com/22441482/63242640-e2ae9880-c20c-11e9-9ee0-750006d79800.png">

Thanks.

**Comment by arnnis** [comment]
I just found out you can use a style prop on Modal component to control the margin.

`
<Modal style={{margin: 0}} />
`

**Comment by oxyii** [comment]
@ziaulrehman40 looks like `style` prop with `{ margin: 0 }` will helps. Something like this:
```jsx
<Modal style={{ margin: 0 }}>
  {yourContent}
</Modal>
```

Source:
https://github.com/Dekoruma/react-native-web-modal/blob/56b12d49390d65527acbf2226541ce1f999c5292/packages/modal-enhanced-react-native-web/src/index.js#L435-L439

**Comment by rayandrew** [comment]
modal is now supported in react native web.

https://github.com/necolas/react-native-web/releases/tag/0.14.0

Thank you for using this library!

<blockquote><img src="https://avatars3.githubusercontent.com/u/239676?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/necolas/react-native-web/releases/tag/0.14.0">Release 0.14.0 · necolas/react-native-web</a></strong></div><div>This is a relatively small release that introduces a couple of new features and makes a change to the default flexBasis value of View. There are no breaking API changes and it should be straight-fo...</div></blockquote>
