### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by TikiTDO** [rayandrews/react-native-web-modal#19]
We use this lib with a `.d.ts` file that looks as follows:

```
declare module "react-native-web-modal" {
  const Modal: typeof import("react-native").Modal
  export = Modal
}
```

Would be great if the lib could do something similar

**Comment by NoMoreViolence** [comment]
plz

**Comment by rayandrew** [comment]
This issue will be on my top priority if I have time. I will rewrite to TS if if possible

**Comment by jimmi-joensson** [comment]
A quick fix for the 'modal-enhanced-react-native-web' based on @TikiTDO post.
You will need to install the [react-native-community/react-native-modal](https://github.com/react-native-community/react-native-modal).
`npm i -D react-native-modal` should suffice.
```
declare module "modal-enhanced-react-native-web" {
  const Modal: typeof import('react-native-modal').ReactNativeModal
  export = Modal
}
```

**Comment by rayandrew** [comment]
modal is now supported in react native web.

https://github.com/necolas/react-native-web/releases/tag/0.14.0

Thank you for using this library!

<blockquote><img src="https://avatars3.githubusercontent.com/u/239676?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/necolas/react-native-web/releases/tag/0.14.0">Release 0.14.0 · necolas/react-native-web</a></strong></div><div>This is a relatively small release that introduces a couple of new features and makes a change to the default flexBasis value of View. There are no breaking API changes and it should be straight-fo...</div></blockquote>
