### ISSUE TITLE
onSwipeComplete never called for enhanced modals

### ISSUE THREAD

**Issue by samdesota** [rayandrews/react-native-web-modal#21]
Thanks for creating this, struggling to get swipe to dismiss to work though:

https://snack.expo.io/@mrapogee/react-native-enhanced-modal-web-onswipecomplete-not-working

This is the base example from @react-native-communitie's react-native-modal, but it looks like onSwipeComplete is never called

**Comment by samdesota** [comment]
Ah, on searching the source I see it's called `onSwipe`, maybe that's on old API. I'll use that as a workaround.

**Comment by rayandrew** [comment]
Closed as resolved
