### ISSUE TITLE
ScrollView doesnt work in modal?

### ISSUE THREAD

**Issue by jameschetwood** [rayandrews/react-native-web-modal#26]
It seems like the `ScrollView` component doesn't do anything in this modal, however the same code works fine with the native modal: https://snack.expo.io/@jamesweblondon/lonely-candies

    <Modal visible={modalOpen}>
        <View>
            <ScrollView>
              {new Array(50).fill("").map((_, index) => {
                return <Text key={index}>Blah {index}</Text>;
              })}
            </ScrollView>
        </View>
      </Modal>

Im a little confused by the docs, they seem to have a scroll version but tell you to install this package:
https://github.com/Dekoruma/react-native-web-modal

However the example code doesn't work for me:
https://snack.expo.io/@jamesweblondon/courageous-donuts

```
  _renderModalContent = () => (
    <View>
      <Text>Hello!</Text>
      {new Array(50).fill("").map((_, index) => {
        return <Text key={index}>Blah {index}</Text>;
      })}
      {this._renderButton("Close", () =>
        this.setState({ visibleModal: false })
      )}
    </View>
  );
```

**Comment by rayandrew** [comment]
modal is now supported in react native web.

https://github.com/necolas/react-native-web/releases/tag/0.14.0

Thank you for using this library!

<blockquote><img src="https://avatars3.githubusercontent.com/u/239676?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/necolas/react-native-web/releases/tag/0.14.0">Release 0.14.0 · necolas/react-native-web</a></strong></div><div>This is a relatively small release that introduces a couple of new features and makes a change to the default flexBasis value of View. There are no breaking API changes and it should be straight-fo...</div></blockquote>
