### ISSUE TITLE
componentWillReceiveProps is now deprecated (there are warnings when using this component)

### ISSUE THREAD

**Issue by mafortier-nexapp** [rayandrews/react-native-web-modal#27]
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#gradual-migration-path

![image](https://user-images.githubusercontent.com/64278521/82164244-94065b80-987d-11ea-9493-066f25a1c513.png)

It's used at the line 59 of `packages/modal-react-native-web/src/index.js`.

**Comment by kopax** [comment]
Why not just submit a PR ? Oh yeah, https://github.com/Dekoruma/react-native-web-modal/pull/25 is open since march and still not merged.

**Comment by rayandrew** [comment]
modal is now supported in react native web.

https://github.com/necolas/react-native-web/releases/tag/0.14.0

Thank you for using this library!

<blockquote><img src="https://avatars3.githubusercontent.com/u/239676?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/necolas/react-native-web/releases/tag/0.14.0">Release 0.14.0 · necolas/react-native-web</a></strong></div><div>This is a relatively small release that introduces a couple of new features and makes a change to the default flexBasis value of View. There are no breaking API changes and it should be straight-fo...</div></blockquote>
