### ISSUE TITLE
Modal seems to override other components styles

### ISSUE THREAD

**Issue by jardg** [rayandrews/react-native-web-modal#29]
Hello. I'm using this library along with react-native-web and React Navigation. I have a problem that happens when I'm on some screen on the website which uses react-native-web-modal. If I push the back button on the browser I navigate to another screen that was displayed properly before. Then when I'm back on the screen the components have lost almost all the styles that they have defined. Also the text doesn't adjust to the width of the screen and creates a scroll. 
This only happens when navigating back from the screen that uses the Modal. If I reload the page everything works fine.

I'm using webpack for bundling

Could you provide me some insight on how to fix this or why this happens? I don't know if I'm doing something wrong and I'm not able to come with a solution that allows me to use react-navigation and this library at the same time. Thanks a lot for any help and of course for the library!

UPDATE: I realized that the bundling process might be the problem. I copied the source code and used from there and now it's working fine!

**Comment by rayandrew** [comment]
modal is now supported in react native web.

https://github.com/necolas/react-native-web/releases/tag/0.14.0

Thank you for using this library!

<blockquote><img src="https://avatars3.githubusercontent.com/u/239676?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/necolas/react-native-web/releases/tag/0.14.0">Release 0.14.0 · necolas/react-native-web</a></strong></div><div>This is a relatively small release that introduces a couple of new features and makes a change to the default flexBasis value of View. There are no breaking API changes and it should be straight-fo...</div></blockquote>
