### ISSUE TITLE
How to install without breaking react native app

### ISSUE THREAD

**Issue by kopax** [rayandrews/react-native-web-modal#32]
After installing and testing the enhanced modal on the web, I am now starting my app with expo and both ios and android app can't start with error:

`ReferenceError: Can't find varialbe: document`.

I presume this should work also on react-native, otherwise it would be called `react-web-modal`, but looking  at the `README.md`, I see no installation step.

How do I configure this package for react native?

Thanks a lot for sharing!

**Comment by kopax** [comment]
I finally manage to get ios/android/web to work with this webpack configuration:

```
  config.resolve.alias['react-native-modal'] = 'modal-enhanced-react-native-web';
```

I had to use the import from react-native-modal in my jsx.

While closing the modal, I see some blicking of the modal on all of those versions, how can I disable it?

**Comment by rayandrew** [comment]
modal is now supported in react native web.

https://github.com/necolas/react-native-web/releases/tag/0.14.0

Could you use the modal in react-native-web? @kopax 
Thank you for using this library!

<blockquote><img src="https://avatars3.githubusercontent.com/u/239676?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/necolas/react-native-web/releases/tag/0.14.0">Release 0.14.0 · necolas/react-native-web</a></strong></div><div>This is a relatively small release that introduces a couple of new features and makes a change to the default flexBasis value of View. There are no breaking API changes and it should be straight-fo...</div></blockquote>
