### ISSUE TITLE
How to make <Menu /> appear on top of everything (and the modal)?

### ISSUE THREAD

**Issue by kopax** [rayandrews/react-native-web-modal#33]
I am using `<Menu />` to create my auto complete field.

Within the `<Modal />`, I am opening the form.

The autocomplete appear under the modal.

How can I make some content over the modal ?

**Comment by rayandrew** [comment]
modal is now supported in react native web.

https://github.com/necolas/react-native-web/releases/tag/0.14.0

Could you use the modal in react-native-web? @kopax 
Thank you for using this library!

<blockquote><img src="https://avatars3.githubusercontent.com/u/239676?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/necolas/react-native-web/releases/tag/0.14.0">Release 0.14.0 · necolas/react-native-web</a></strong></div><div>This is a relatively small release that introduces a couple of new features and makes a change to the default flexBasis value of View. There are no breaking API changes and it should be straight-fo...</div></blockquote>
