### ISSUE TITLE
Not closing properly with react-native-web 0.13.7

### ISSUE THREAD

**Issue by uxxman** [rayandrews/react-native-web-modal#35]
After upgrading to react-native-web 0.13.7, the modal close function is showing/hiding modal 2 times on close

![Screen-Recording-2020-09-30-at-13 00 14](https://user-images.githubusercontent.com/3153380/94677660-972a5180-031d-11eb-8a1a-2baf46faf325.gif)

**Comment by nkumar-ee** [comment]
I am too facing similar issue after upgrading 0.13.7

**Comment by uxxman** [comment]
@nkumar-ee did you find a fix for this?

**Comment by sonnyp** [comment]
react-native-web 0.14 was released with support for modals https://github.com/necolas/react-native-web/releases/tag/0.14.0

<blockquote><img src="https://avatars3.githubusercontent.com/u/239676?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/necolas/react-native-web/releases/tag/0.14.0">Release 0.14.0 · necolas/react-native-web</a></strong></div><div>This is a relatively small release that introduces a couple of new features and makes a change to the default flexBasis value of View. There are no breaking API changes and it should be straight-fo...</div></blockquote>

**Comment by rayandrew** [comment]
modal is now supported in react native web.
there is no point on continuing this library.

https://github.com/necolas/react-native-web/releases/tag/0.14.0

I will close this

<blockquote><img src="https://avatars3.githubusercontent.com/u/239676?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/necolas/react-native-web/releases/tag/0.14.0">Release 0.14.0 · necolas/react-native-web</a></strong></div><div>This is a relatively small release that introduces a couple of new features and makes a change to the default flexBasis value of View. There are no breaking API changes and it should be straight-fo...</div></blockquote>

**Comment by basithrehman** [comment]
> modal is now supported in react native web.
> there is no point on continuing this library.
> 
> https://github.com/necolas/react-native-web/releases/tag/0.14.0
> 
> I will close this
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/239676?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Release 0.14.0 · necolas/react-native-web](/necolas/react-native-web/releases/tag/0.14.0)**This is a relatively small release that introduces a couple of new features and makes a change to the default flexBasis value of View. There are no breaking API changes and it should be straight-fo...

Came here just to know React-native-modal is supported in web now. Kudos to your contributions!

<blockquote><img src="https://repository-images.githubusercontent.com/37153337/9d0a6780-394a-11eb-9fd1-6296a684b124" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/necolas/react-native-web/releases/tag/0.14.0">Release 0.14.0 · necolas/react-native-web</a></strong></div><div>This is a relatively small release that introduces a couple of new features and makes a change to the default flexBasis value of View. There are no breaking API changes and it should be straight-fo...</div></blockquote>
