### ISSUE TITLE
Modal crash in react-native app

### ISSUE THREAD

**Issue by FilipMessa** [rayandrews/react-native-web-modal#8]
I am trying to use your modal as a universal Modal component, but it works only for the web in the react-native application It crash:
"window.addEventListener is undefined"

<img width="420" alt="screen shot 2018-11-06 at 14 53 14" src="https://user-images.githubusercontent.com/6354326/48068660-b7a20d80-e1d3-11e8-9ced-28c70c446cf4.png">

**Comment by rayandrew** [comment]
Hi @FilipMessa,

Do not use it on react native, instead use 
- [Modal](https://facebook.github.io/react-native/docs/modal) in React Native for the base
- or [React Native Modal](https://github.com/react-native-community/react-native-modal) for the enhanced version

This library only works with React Native Web __NOT__ React Native.

__To conclude, it only works in web__

I hope it helps @FilipMessa 

Note :
If you use multi-environment build for both web and native, you can use webpack alias to rename the Modal package to this library if you build it on web
